### ISSUE TITLE
Filters for Ward Rounds

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/opal-wardround#17] opened 2015-01-20 17:43 UTC
- [ ] Name/number filter for names on list when you view the list (like on team lists)

**Comment by GabPoll** [comment] 2015-01-21 12:57
+1 - specifically mentioned with no prompting by VG yesterday.

**Comment by davidmiller** [comment] 2015-01-29 15:29
Duplicate of #14 - closing ! :)

**Closed by davidmiller** 2015-01-29 15:29 UTC
Labels: enhancement
